apiVersion: v1
kind: Service
metadata:
  name: db-delivery-new
spec:
  type: ClusterIP
  ports:
    - name: "db-delivery-new"
      port: 5432
      targetPort: 5432
  selector:
    app: db-delivery-new