apiVersion: v1
kind: Service
metadata:
  name: delivery-service-new
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8100
      targetPort: 8100
  selector:
    app: delivery-service-new