apiVersion: v1
kind: Service
metadata:
  name: firm-service-new
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8120
      targetPort: 8120
  selector:
    app: firm-service-new