apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediator-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediator-new
  template:
    metadata:
      labels:
        app: mediator-new
    spec:
      containers:
        -
          image: poltorakyevheniia/mediator-new
          name: mediator-new
          ports:
            - containerPort: 8081
              name: rest
