apiVersion: v1
kind: Service
metadata:
  name: order-service-new
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8090
      targetPort: 8090
  selector:
    app: order-service-new